#!/bin/bash

# explicitly set path, since from cron, we don't inherit it (or read .bashrc).
export PATH=/opt/upgrade-alsa/installdir/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/amon/amon

# umask to ensure others can read files we generate
umask 0022 

# get the pid of this instance of amon
AMONPID=$$

# always cd to amondir to make paths simple.
AMONDIR=`dirname $0`
cd ${AMONDIR}

### read the config file(s) and function definitions.
[ ! -r defs.sh ] && echo "Fatal: no config file defs.sh. I give up." && exit -1
source defs.sh

[ ! -r amon.conf ] && echo "Fatal: no config file amon.conf. I give up." && exit -1
source amon.conf

[ -r /boot/solo/amon.conf ] && { 
#    echo "Reading additional config file: /boot/solo/amon.conf" 
    source /boot/solo/amon.conf
}

# added this for desktop users, who want to have personalized config,
# but don't want to make a /boot/solo directory on their desktop.
# [its very useful in debug/dev work too, so git doesn't complain
# about the local amon.conf being wrongly set up for the desktop audio
# settings ]
[ -r $HOME/.amon.conf ] && {
    echo "[Reading additional config file: $HOME/.amon.conf]"
    source $HOME/.amon.conf
}

if [ ! -d $AMONDATA ] ; then
    echo "Warning: can't find output directory $AMONDATA - instead using $AMONDIR/amondata"
    AMONDATA=$AMONDIR/amondata
    mkdir -p $AMONDATA
fi

### these must come AFTER reading the configs (really?)
WAVDIR=${AMONDATA}/wavs
LOGDIR=${AMONDATA}/logs
ALOG=${LOGDIR}/arecord.log
AMONLOG=${LOGDIR}/amon.log
STATEFILE=${LOGDIR}/amon.state
PIDFILE=${LOGDIR}/arecord.pid

# Build the directory for wav files
if [ ! -d $WAVDIR ] ; then
    log "INFO: Creating data directory \"$WAVDIR\" for audio files"
    mkdir $WAVDIR 
fi

# Build log directory
if [ ! -d $LOGDIR ] ; then
    log "INFO: Creating data directory \"$LOGDIR\" for logs"
    mkdir $LOGDIR 
fi

# Initialise 'state' file?
if [ ! -r $STATEFILE ] ; then
  log "INFO: No statefile \"$STATEFILE\" - creating one ... "

  # Perhaps conf prescribed "off" or "on"???
  # choose logic so that if it is _anything_ but "off", we are on.
  if [ -n "$MASTERSWITCH" ] ; then
      log "Read MASTERSWITCH value from conf of \"$MASTERSWITCH\""
      if [ "$MASTERSWITCH" != "off" -a "$MASTERSWITCH" != "on"] ; then
	  log "Warning: badly formed MASTERSWITCH value of $MASTERSWITCH.  Assuming: \"on\""
	  MASTERSWITCH="on"
       fi
  else
      MASTERSWITCH=on
  fi

  log "Creating statefile: amon MASTERSWITCH is \"$MASTERSWITCH\""
  echo "$MASTERSWITCH" > $STATEFILE      
fi


##########################################
# parse command line
##########################################

# The user has typed something like "amon status".  The code below
# uses "type -t" to ensure there is a function called either
# "amonstatus" or "status", and then executes it.  Thus functions can
# be developed independently of informing this "command line parser"
# about them.

# must say something
[ $# -eq 0 ] && { amonhelp; exit 0;}

if [ xx`type -t amon${1}` = xx"function" ] ; then
    amon${1} $*
elif [ xx`type -t $1` = xx"function" ] ; then
    $1 $*
else
    echo "amon: \"$1\": command not known to amon"
fi

exit 0
